on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y fakeroot debhelper dh-systemd

      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Build deb package
        run: dpkg-buildpackage -us -uc -b

      - name: See what we got
        run: |
          ls -la
          ls -la ../
